server:
  port: 8085
  contextPath: "/"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mr
    username: postgres
    password: 1234
    generate-ddl: false
jwt:
  expireDays: 3000
  refreshDays: 3
  secret: jhrstbojsetoibneaascac